(define (problem pb2)
   (:domain blocksworld)
   (:requirements :strips :equality :negative-preconditions)
   (:objects a b)
   (:init (on-table a) (on-table b)  (clear a)  (clear b) (arm-empty) )
   (:goal (and (on a b)     )))